# Generated by Django 4.0.5 on 2023-03-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenge_V2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('phoneId', models.AutoField(primary_key=True, serialize=False)),
                ('phoneName', models.CharField(max_length=50)),
                ('lastLoginTime', models.DateTimeField(auto_now=True)),
                ('cookie', models.JSONField()),
            ],
        ),
    ]
