# Generated by Django 4.0.5 on 2023-03-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenge_V2_app', '0002_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='cookie',
            field=models.CharField(max_length=300),
        ),
    ]
