# Generated by Django 4.0.5 on 2023-03-07 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wenge_V2_app', '0003_alter_phone_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='usedByPhone',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='tiktokId',
            field=models.CharField(default=None, max_length=50)
        ),
    ]
