# Generated by Django 4.0.5 on 2023-03-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenge_V2_app', '0004_account_usedbyphone_phone_tiktokid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='tiktokId',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
