# Generated by Django 4.0.5 on 2023-03-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenge_V2_app', '0005_alter_phone_tiktokid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='extraEmail',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='usedByPhone',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
