# Generated by Django 4.0.5 on 2023-03-08 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wenge_V2_app', '0006_account_extraemail_alter_account_usedbyphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='createdTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='phone',
            name='IP',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='extraEmail',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='usedByPhone',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
