# Generated by Django 4.0.5 on 2023-03-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenge_V2_app', '0007_account_createdtime_phone_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(0, '未使用'), (1, '已使用'), (2, '已封禁')], default=0),
        ),
    ]
